apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: clone-read-run
  namespace: user4
spec:
  pipelineRef:
    name: clone-read
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: github-secret
    secret:
      secretName: github-secret
  params:
  - name: repo-url
    value: https://github.com/ecno20/paciente-service/
