apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: paciente
  name: paciente
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8084
  selector:
    app: paciente
  type: ClusterIP
