apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: kubernetes-actions-
spec:
  taskRef:
    name: kubernetes-actions
  params:
    - name: script
      value: |
        kubectl delete deployment paciente-service
        kubectl create deployment paciente-service --image=docker.io/ecno20/cloud-paciente-service:1.0
        echo "----------"
        kubectl get deployment
  workspaces:
    - name: kubeconfig-dir
      emptyDir: {}
    - name: manifest-dir
      emptyDir: {}
  serviceAccountName: tekton-pipeline
