apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: list-directory-subdir-
spec:
  taskRef:
    kind: Task
    name: list-directory
  params:
  - name: "sub-dirs"
    value: 
    - target
  workspaces:
    - name: directory
      persistentVolumeClaim:
        claimName: shared-workspace
